### ISSUE TITLE
Local files broken

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#271]
With the last update, local files sync crashes the app. I sent you the logs by email, and the only way I could open the app was to remove photos permission

**Comment by nagarrido** [comment]
I tried to replicate this in another device with about 5 local photos, and it worked fine. The device that is failing has 8000+ local photos (from WhatsApp). Maybe it could be something related to the number of local files?

**Comment by savvasdalkitsis** [comment]
I believe this is now fixed @nagarrido. Once the new version is released, let me know if that is the case. If not, please reopen this issue

**Comment by nagarrido** [comment]
Hi, it seems it's still happening 😔 I sent you the logs again, but it seems to me the error is the same
